### ISSUE TITLE
Incorrect result for stochastic

### ISSUE THREAD

**Issue by ourarash** [anandanand84/technicalindicators#109]
I tried this data (sorry if it's too long):

[runkit link](https://runkit.com/ourarash/stochastic
)

But the result seems incorrect. `d` remains undefined.

**Comment by gauravchauhan** [comment]
I am also facing same issue https://runkit.com/embed/s41ke7eaefwm

**Comment by anandanand84** [comment]
This happens when the close, high and low are same for the entire period; I'll add a fix

Thankyou

**Comment by anandanand84** [comment]
Fixed on version 1.1.5

**Comment by JanMesaric** [comment]
I'm using 1.1.8 and when having multiple same high, low, close it still returns Object {d: undefined, k: NaN}

**Comment by JMoli** [comment]
@JanMesaric How long is the dataset? This can still occur if your period is as long or shorter than the dataset. Try with the data posted by OP to confirm

**Comment by JanMesaric** [comment]
@JMoli , correct, didn't see that.
